
language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - pytest

deploy:
  - provider: pypi
    distributions: sdist bdist_wheel
    user: <username>
    password:
      secure: <encrypted password>
    skip_existing: true
    on:
      tags: true
